version: "3.7"                                                                                            
services:                                                                                                 
  dashboard-fe:                                                                                           
    build: .                                                                                              
    healthcheck:                                                                                          
      test: curl -f http://localhost                                                                      
      interval: 30s                                                                                       
      timeout: 3s                                                                                         
    ports:                                                                                                
      - "8089:443"                                                                                         
    restart: always                                                                                       

networks:                                                                                                 
  default:                                                                                                
    external:                                                                                             
      name: jarvis-vina
